# FUENTE
font_family      JetBrainsMono Nerd Font
font_size        11.5

# VENTANA
window_padding_width 12
background_opacity 0.92
dynamic_background_opacity yes

# CURSOR
cursor_shape block
cursor_blink_interval 0

# COLORES
# foreground            #e8e8e8
# background            #0c0c0c
# selection_foreground  #ffffff
# selection_background  #333333
# color0  #151515
# color1  #d75f5f
# color2  #87af87
# color3  #d7af87
# color4  #87afd7
# color5  #af87af
# color6  #87afaf
# color7  #d0d0d0
# color8  #555555
# color9  #d78787
# color10 #afd7af
# color11 #d7d787
# color12 #87afd7
# color13 #d7afd7
# color14 #afd7d7
# color15 #ffffff

# PESTAÑAS
tab_bar_style powerline
tab_powerline_style slanted
# active_tab_foreground   #ffffff
# active_tab_background   #292929
# inactive_tab_foreground #888888
# inactive_tab_background #151515

# OTROS
confirm_os_window_close 0
enable_audio_bell no


# BEGIN_KITTY_THEME
# Alabaster Dark
include current-theme.conf
# END_KITTY_THEME