general {
    lock_cmd = pidof hyprlock || hyprlock
    before_sleep_cmd = loginctl lock-session
    after_sleep_cmd = hyprctl dispatch dpms on
}

# 10 minutos -> bloquear
listener {
    timeout = 600
    on-timeout = loginctl lock-session
}

# 15 minutos -> apagar monitores
listener {
    timeout = 900
    on-timeout = hyprctl dispatch dpms off
    on-resume = hyprctl dispatch dpms on
}

# 45 minutos -> suspender PC
#listener {
#    timeout = 2700
#    on-timeout = systemctl suspend
#}
